windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class org.pulseaudio.pavucontrol, size 800 600

windowrule = match:initial_class steam, match:initial_title negative:Steam, float on

windowrule = match:title (Exiled Exchange 2), tag +ee2
windowrule = match:tag ee2, no_blur on
